### ISSUE TITLE
Bug in line no7 of the code

### ISSUE THREAD

**Issue by mousamiaws** [mousamiaws/Devops_Mousami#2]
Dear team 
there is a bug in line 7. please correct it.
![AWS SCREENSHOT](https://user-images.githubusercontent.com/79818305/109444335-4026c680-79fa-11eb-9633-4c8ffd4385dd.png)

**Comment by bipeensinha** [comment]
ok Mausmi , We will work and uopdate you

**Comment by swatiawsarchitect** [comment]
test_comment

**Comment by bipeensinha** [comment]
![code](https://user-images.githubusercontent.com/49720823/109444433-3be2c380-7a63-11eb-8846-053a3a4534a6.jpg)
I fix it up . we can now move ahead for build

**Comment by mousamiaws** [comment]
thank you so much.
